import type { Story } from './storyTypes';

export const story: Story = {
  title: 'DeViz Data Story',
  subtitle: 'Interactive Health Center Data Visualization',
  scenes: [
    {
      id: 'scene00_cognitive_map',
      title: 'Story Navigation',
      subtitle: 'Navigate the journey from data collection to research insights',
      component: 'scene00_cognitive_map',
      notes: 'Visual roadmap of all story sections and their relationships',
      detailLevel: 'both',
    },
    {
      id: 'scene01_introduction',
      title: 'Introduction to NAMCS Health Center Data',
      subtitle: 'Three pillars: Microdata, dashboards, and linkage',
      component: 'scene01_pillars',
      notes: 'Hover nodes to see definitions',
      relatedScenes: ['scene07', 'scene11'],
      detailLevel: 'both',
    },
    {
      id: 'scene02',
      title: 'Who FQHCs serve and why it matters',
      subtitle: 'Health centers in shortage areas and equity context',
      component: 'scene02_fqhc_map',
      notes: 'Geographic distribution and patient populations',
      relatedScenes: ['scene04', 'scene09'],
      detailLevel: 'beginner',
    },
    {
      id: 'scene03',
      title: 'Redesign shift in 2021',
      subtitle: 'From abstraction to full year EHR submissions',
      component: 'scene03_before_after',
      notes: 'Transformation from manual to automated collection',
      relatedScenes: ['scene05', 'scene06'],
      detailLevel: 'both',
    },
    {
      id: 'scene04',
      title: 'Participation growth and scale',
      subtitle: 'Centers and visit records expand over time',
      component: 'scene04_growth',
      notes: 'Growth from 29 to 95+ participating centers',
      relatedScenes: ['scene02', 'scene07'],
      detailLevel: 'both',
    },
    {
      id: 'scene05',
      title: 'Evolution timeline',
      subtitle: 'From manual abstraction to automated EHR collection',
      component: 'scene05_timeline',
      notes: 'Key milestones in data collection evolution',
      relatedScenes: ['scene03', 'scene06'],
      detailLevel: 'beginner',
    },
    {
      id: 'scene06',
      title: 'Data collection pipeline',
      subtitle: 'Recruit, questionnaire, HL7 install, test, submit',
      component: 'scene06_pipeline',
      notes: 'Step-by-step data collection process',
      relatedScenes: ['scene05', 'scene07'],
      detailLevel: 'expert',
    },
    {
      id: 'scene07',
      title: 'Data file types and coverage',
      subtitle: 'Restricted versus public variable coverage',
      component: 'scene07_data_matrix',
      notes: 'What data is available in each file format',
      relatedScenes: ['scene01_introduction', 'scene08'],
      detailLevel: 'both',
    },
    {
      id: 'scene08',
      title: 'Access paths for researchers',
      subtitle: 'Public download versus RDC route',
      component: 'scene08_access_paths',
      notes: 'How researchers can obtain and use the data',
      relatedScenes: ['scene07', 'scene11'],
      detailLevel: 'both',
    },
    {
      id: 'scene09',
      title: 'Maternal health insights',
      subtitle: 'Visit patterns and gestational diabetes trends',
      component: 'scene09_maternal',
      notes: 'Real-world health outcomes and patterns',
      relatedScenes: ['scene02', 'scene10'],
      detailLevel: 'beginner',
    },
    {
      id: 'scene10',
      title: 'Respiratory health disparities',
      subtitle: 'Asthma, COPD, and influenza by demographics',
      component: 'scene10_respiratory',
      notes: 'Health equity patterns in respiratory conditions',
      relatedScenes: ['scene09', 'scene11'],
      detailLevel: 'beginner',
    },
    {
      id: 'scene11',
      title: 'Data linkage capabilities',
      subtitle: 'Connecting to HUD, NDI, and Medicaid databases',
      component: 'scene11_linkage_power',
      notes: 'Enhanced research through cross-database connections',
      relatedScenes: ['scene01_introduction', 'scene08'],
      detailLevel: 'both',
    },
    {
      id: 'scene12',
      title: 'Linkage rates and coverage',
      subtitle: 'Success rates and match patterns across datasets',
      component: 'scene12_linkage_rates',
      notes: 'Technical details of linkage performance',
      relatedScenes: ['scene11', 'scene13'],
      detailLevel: 'expert',
    },
    {
      id: 'scene13',
      title: 'Limitations and data quality',
      subtitle: 'Understanding constraints and appropriate use',
      component: 'scene13_limitations',
      notes: 'Known limitations and quality considerations',
      relatedScenes: ['scene12', 'scene14'],
      detailLevel: 'both',
    },
    {
      id: 'scene14',
      title: 'Development roadmap',
      subtitle: 'Future enhancements and expansion plans',
      component: 'scene14_roadmap',
      notes: 'Timeline of planned improvements',
      relatedScenes: ['scene13', 'scene15'],
      detailLevel: 'both',
    },
    {
      id: 'scene15',
      title: 'Synthesis',
      subtitle: 'Before and after: The research transformation',
      component: 'scene15_synthesis',
      notes: 'Closing summary of the NAMCS HC impact',
      relatedScenes: ['scene14', 'scene01_introduction'],
      detailLevel: 'both',
    },
  ],
};
