import type { Story } from './storyTypes';

export const story: Story = {
  title: 'NAMCS Health Center Data',
  subtitle: 'Microdata, dashboards, and linkage for patient centered outcomes research',
  scenes: [
    {
      id: 'scene01_introduction',
      title: 'Introduction to NAMCS Health Center Data',
      subtitle: 'Microdata, dashboards, and linkage',
      component: 'scene01_pillars',
      notes: 'Hover nodes to see definitions',
    },
    {
      id: 'scene02',
      title: 'Who FQHCs serve and why it matters',
      subtitle: 'Health centers in shortage areas and equity context',
      component: 'scene02_fqhc_map',
      notes: 'Placeholder map scene',
    },
    {
      id: 'scene03',
      title: 'Redesign shift in 2021',
      subtitle: 'From abstraction to full year EHR submissions',
      component: 'scene03_before_after',
      notes: 'Placeholder split panel scene',
    },
    {
      id: 'scene04',
      title: 'Participation growth and scale',
      subtitle: 'Centers and visit records expand over time',
      component: 'scene04_growth',
      notes: 'Uses Table 1 starter values',
    },
    {
      id: 'scene05',
      title: 'Evolution timeline',
      subtitle: 'From manual abstraction to automated EHR collection',
      component: 'scene05_timeline',
      notes: 'Zigzag timeline showing the redesign progression',
    },
    {
      id: 'scene06',
      title: 'Data collection pipeline',
      subtitle: 'Recruit, questionnaire, HL7 install, test, submit',
      component: 'scene06_pipeline',
      notes: 'Placeholder flow scene',
    },
    {
      id: 'scene07',
      title: 'What data exists in each file type',
      subtitle: 'Restricted versus public variable coverage',
      component: 'scene07_data_matrix',
      notes: 'Placeholder matrix scene',
    },
    {
      id: 'scene08',
      title: 'Access paths for researchers',
      subtitle: 'Public download versus RDC route',
      component: 'scene08_access_paths',
      notes: 'Placeholder journey scene',
    },
    {
      id: 'scene09',
      title: 'Maternal health example',
      subtitle: 'Visit rates by age group plus gestational diabetes',
      component: 'scene09_maternal',
      notes: 'Uses Table 2 starter rates',
    },
    {
      id: 'scene10',
      title: 'Dashboards for broader PCOR',
      subtitle: 'Interactive preliminary estimates without code',
      component: 'scene10_dashboard_mock',
      notes: 'Placeholder dashboard mock scene',
    },
    {
      id: 'scene11',
      title: 'Respiratory disparities example',
      subtitle: 'Rates by race and ethnicity over biannual periods',
      component: 'scene11_respiratory_disparities',
      notes: 'Placeholder line chart scene',
    },
    {
      id: 'scene12',
      title: 'Linkage power',
      subtitle: 'HUD, NDI, and external sources',
      component: 'scene12_linkage_power',
      notes: 'Placeholder bipartite graph scene',
    },
    {
      id: 'scene13',
      title: 'Linkage rates and who links',
      subtitle: 'Age and sex linkage percentages',
      component: 'scene13_linkage_rates',
      notes: 'Placeholder small multiples scene',
    },
    {
      id: 'scene14',
      title: 'Limitations and data quality',
      subtitle: 'Response rates, missingness, public exclusions, linkage years',
      component: 'scene14_limitations',
      notes: 'Placeholder limitations scene',
    },
    {
      id: 'scene15',
      title: 'Roadmap',
      subtitle: 'New files, dashboards, and linkages',
      component: 'scene15_roadmap',
      notes: 'Placeholder roadmap scene',
    },
    {
      id: 'scene16',
      title: 'Choose your own PCOR path',
      subtitle: 'Dashboard, public file, restricted file, or linkage',
      component: 'scene16_choose_path',
      notes: 'Placeholder decision tree scene',
    },
    {
      id: 'scene17',
      title: 'Synthesis',
      subtitle: 'Pillars, personas, and takeaways',
      component: 'scene17_synthesis',
      notes: 'Placeholder closing scene',
    },
  ],
};
